apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::080120290987:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-95SMGRJYIR2L
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::080120290987:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-14T19:15:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1387"
  uid: 9490175f-b650-4086-b1c9-4d06efc334bc
